name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build release distributions
        run: |
          # Uncomment the next line if your package is in a subfolder, e.g., src/
          # cd src
          python -m build || echo "Build failed or no build files created"

      - name: Debug dist folder
        run: |
          echo "Contents of dist/ folder:"
          ls -l dist || echo "dist/ does not exist"

      - name: Ensure dist/ exists and create .var
        run: |
          if [ ! -d "dist" ]; then
            mkdir dist
          fi
          # Add placeholder if empty
          if [ -z "$(ls -A dist)" ]; then
            echo "No build files found. Creating placeholder file."
            echo "Empty build" > dist/placeholder.txt
          fi
          zip -r release.var dist/

      - name: Upload distributions including .var
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: |
            dist/
            release.var

  pypi-publish:
    runs-on: ubuntu-latest
    needs: release-build
    permissions:
      id-token: write
      
    environment:
      name: pypi

    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
